/** @type {import('tailwindcss').Config} */
export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                // Saffron Horizon — The Digital Concierge palette
                primary: '#ab2d00',
                'primary-dim': '#962700',
                'primary-container': '#ff7851',
                'primary-fixed': '#ff7851',
                'primary-fixed-dim': '#ff5d2b',
                'on-primary': '#ffefeb',
                'on-primary-container': '#470e00',
                'on-primary-fixed': '#000000',
                'on-primary-fixed-variant': '#581300',
                secondary: '#a03739',
                'secondary-dim': '#902c2e',
                'secondary-container': '#ffc3c0',
                'secondary-fixed': '#ffc3c0',
                'secondary-fixed-dim': '#ffafac',
                'on-secondary': '#ffefee',
                'on-secondary-container': '#852327',
                'on-secondary-fixed': '#6a0e16',
                'on-secondary-fixed-variant': '#922d2f',
                tertiary: '#833e9a',
                'tertiary-dim': '#76318d',
                'tertiary-container': '#e699fd',
                'tertiary-fixed': '#e699fd',
                'tertiary-fixed-dim': '#d88cee',
                'on-tertiary': '#ffedfe',
                'on-tertiary-container': '#570e6f',
                'on-tertiary-fixed': '#360049',
                'on-tertiary-fixed-variant': '#611b79',
                error: '#b31b25',
                'error-dim': '#9f0519',
                'error-container': '#fb5151',
                'on-error': '#ffefee',
                'on-error-container': '#570008',
                background: '#fff4f3',
                'on-background': '#4e2120',
                surface: '#fff4f3',
                'surface-dim': '#ffc7c4',
                'surface-bright': '#fff4f3',
                'surface-tint': '#ab2d00',
                'surface-variant': '#ffd2d0',
                'surface-container': '#ffe1e0',
                'surface-container-low': '#ffedeb',
                'surface-container-lowest': '#ffffff',
                'surface-container-high': '#ffdad8',
                'surface-container-highest': '#ffd2d0',
                'on-surface': '#4e2120',
                'on-surface-variant': '#834c4b',
                'inverse-surface': '#240304',
                'inverse-on-surface': '#ce8c89',
                'inverse-primary': '#ff5722',
                outline: '#a26765',
                'outline-variant': '#e09c99',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                md: '0.75rem',
                lg: '1rem',
                xl: '1.5rem',
                '2xl': '2rem',
                '3xl': '2.5rem',
                full: '9999px',
            },
            fontFamily: {
                headline: ['"Plus Jakarta Sans"', 'system-ui', 'sans-serif'],
                body: ['Inter', 'system-ui', 'sans-serif'],
                label: ['Inter', 'system-ui', 'sans-serif'],
                sans: ['Inter', 'system-ui', 'sans-serif'],
            },
            backgroundImage: {
                'editorial-gradient': 'linear-gradient(135deg, #ab2d00 0%, #ff7851 100%)',
            },
            boxShadow: {
                editorial: '0 12px 40px rgba(78, 33, 32, 0.06)',
                'editorial-lg': '0 20px 60px rgba(78, 33, 32, 0.12)',
            },
        },
    },
    plugins: [],
}