import type { Notification, NotificationType } from '@types/notification'

const AV = (seed: string) =>
  `https://images.unsplash.com/photo-${seed}?auto=format&fit=crop&w=200&q=80`
const IMG = (seed: string) =>
  `https://images.unsplash.com/photo-${seed}?auto=format&fit=crop&w=900&q=80`

export const NOTIFICATION_ICON: Record<NotificationType, string> = {
  booking_new: 'event_available',
  booking_confirmed: 'check_circle',
  booking_cancelled: 'event_busy',
  review_new: 'star',
  comment: 'chat_bubble',
  like: 'favorite',
  follow: 'person_add',
  payout: 'payments',
  message: 'mail',
  system: 'campaign',
  guide_application: 'workspace_premium',
  trip_update: 'flight_takeoff',
}

export const NOTIFICATION_TONE: Record<NotificationType, string> = {
  booking_new: 'bg-amber-500/15 text-amber-700',
  booking_confirmed: 'bg-green-500/15 text-green-700',
  booking_cancelled: 'bg-error/10 text-error',
  review_new: 'bg-primary/10 text-primary',
  comment: 'bg-secondary/10 text-secondary',
  like: 'bg-rose-500/15 text-rose-600',
  follow: 'bg-tertiary/10 text-tertiary',
  payout: 'bg-green-500/15 text-green-700',
  message: 'bg-primary/10 text-primary',
  system: 'bg-on-surface/10 text-on-surface',
  guide_application: 'editorial-gradient text-on-primary',
  trip_update: 'bg-primary/10 text-primary',
}

export const mockNotifications: Notification[] = [
  {
    id: 'n1',
    type: 'booking_new',
    title: 'Booking mới từ Maya Lee',
    preview: 'Du thuyền 3 ngày khám phá Vịnh · 4 khách · ₫3.600.000',
    body: 'Maya Lee vừa gửi yêu cầu đặt tour "Du thuyền 3 ngày khám phá Vịnh Hạ Long" cho 4 khách trong 3 ngày (15-17/12/2024). Bạn có 24h để xác nhận trước khi yêu cầu tự huỷ.',
    createdAt: '2 giờ trước',
    isoDate: '2024-12-08T10:24:00',
    read: false,
    actor: { id: 'u1', name: 'Maya Lee', avatar: AV('1502823403499-6ccfcf4fb453') },
    ctaLabel: 'Xem booking',
    ctaHref: '/guide/dashboard',
    image: IMG('1528127269322-539801943592'),
    meta: [
      { label: 'Tour', value: 'Du thuyền 3 ngày Vịnh Hạ Long', icon: 'tour' },
      { label: 'Ngày khởi hành', value: '15/12/2024', icon: 'event' },
      { label: 'Số khách', value: '4 người', icon: 'groups' },
      { label: 'Tổng tiền', value: '₫3.600.000', icon: 'payments' },
    ],
  },
  {
    id: 'n2',
    type: 'review_new',
    title: 'Maya Lee đã đánh giá 5 sao',
    preview: '"Một trải nghiệm khó quên! HDV cực kỳ am hiểu..."',
    body: 'Maya Lee vừa để lại đánh giá 5 sao cho tour "Du thuyền 3 ngày Vịnh Hạ Long" của bạn. "Một trải nghiệm khó quên! HDV cực kỳ am hiểu và nhiệt tình, đưa nhóm mình đến những nơi mà bình thường du khách không thể tìm thấy."',
    createdAt: '5 giờ trước',
    isoDate: '2024-12-08T07:24:00',
    read: false,
    actor: { id: 'u1', name: 'Maya Lee', avatar: AV('1502823403499-6ccfcf4fb453') },
    ctaLabel: 'Phản hồi đánh giá',
    ctaHref: '/guide/dashboard',
    meta: [
      { label: 'Đánh giá', value: '★★★★★ (5/5)', icon: 'star' },
      { label: 'Tour', value: 'Du thuyền 3 ngày', icon: 'tour' },
    ],
  },
  {
    id: 'n3',
    type: 'comment',
    title: 'Minh Trần đã bình luận bài viết của bạn',
    preview: '"Tuyệt quá! Bạn ở khu nào vậy? Mình đang lên kế hoạch..."',
    body: 'Minh Trần vừa bình luận trên bài viết "Đêm phố cổ và những chiếc đèn lồng" của bạn: "Tuyệt quá! Bạn ở khu nào vậy? Mình đang lên kế hoạch tháng sau."',
    createdAt: '8 giờ trước',
    isoDate: '2024-12-08T04:24:00',
    read: false,
    actor: { id: 'u2', name: 'Minh Trần', avatar: AV('1500648767791-00dcc994a43e') },
    ctaLabel: 'Xem bài viết',
    ctaHref: '/social',
  },
  {
    id: 'n4',
    type: 'like',
    title: '12 người đã thích bài viết của bạn',
    preview: 'Linh, Alex và 10 người khác đã thích "Đêm phố cổ..."',
    body: 'Linh Nguyễn, Alex Nguyễn và 10 người khác vừa thích bài viết "Đêm phố cổ và những chiếc đèn lồng" của bạn.',
    createdAt: '12 giờ trước',
    isoDate: '2024-12-08T00:24:00',
    read: true,
    actor: { id: 'u1', name: 'Linh Nguyễn', avatar: AV('1494790108377-be9c29b29330') },
    ctaLabel: 'Xem bài viết',
    ctaHref: '/social',
  },
  {
    id: 'n5',
    type: 'follow',
    title: 'Elena Trần đang theo dõi bạn',
    preview: 'Elena là HDV ở Hội An — có 5 chuyến đi sắp tới.',
    body: 'Elena Trần — một traveler từ Đà Lạt — vừa bắt đầu theo dõi bạn để cập nhật các chuyến đi sắp tới.',
    createdAt: '1 ngày trước',
    isoDate: '2024-12-07T12:24:00',
    read: true,
    actor: { id: 'u3', name: 'Elena Trần', avatar: AV('1438761681033-6461ffad8d80') },
    ctaLabel: 'Xem hồ sơ',
    ctaHref: '/guides/hg2',
  },
  {
    id: 'n6',
    type: 'payout',
    title: 'Đã nhận thanh toán ₫18.800.000',
    preview: 'TravelSocial vừa chuyển doanh thu tháng 11 vào Vietcombank ****1234.',
    body: 'Khoản thanh toán ₫18.800.000 (doanh thu tháng 11/2024) đã được TravelSocial chuyển vào tài khoản Vietcombank ****1234 của bạn vào ngày 01/12/2024.',
    createdAt: '5 ngày trước',
    isoDate: '2024-12-03T10:00:00',
    read: true,
    ctaLabel: 'Xem chi tiết doanh thu',
    ctaHref: '/guide/dashboard',
    meta: [
      { label: 'Số tiền', value: '₫18.800.000', icon: 'payments' },
      { label: 'Ngày', value: '01/12/2024', icon: 'event' },
      { label: 'Phương thức', value: 'Vietcombank ****1234', icon: 'account_balance' },
      { label: 'Trạng thái', value: 'Đã thanh toán', icon: 'check_circle' },
    ],
  },
  {
    id: 'n7',
    type: 'guide_application',
    title: 'Hồ sơ HDV đã được duyệt 🎉',
    preview: 'Bạn chính thức là Hướng dẫn viên TravelSocial.',
    body: 'Chúc mừng! Hồ sơ HDV của bạn đã được duyệt sau 4 ngày làm việc. Từ giờ bạn có thể tạo tour, nhận booking và quản lý doanh thu trong khu vực dành cho HDV.',
    createdAt: '1 tuần trước',
    isoDate: '2024-12-01T09:00:00',
    read: true,
    ctaLabel: 'Vào quản lý Guide',
    ctaHref: '/guide/dashboard',
  },
  {
    id: 'n8',
    type: 'system',
    title: 'Cập nhật chính sách hoa hồng',
    preview: 'Phí TravelSocial áp dụng từ 01/01/2025 sẽ là 12% (giảm từ 15%).',
    body: 'TravelSocial đang điều chỉnh chính sách hoa hồng để hỗ trợ HDV nhiều hơn. Từ 01/01/2025, phí nền tảng giảm còn 12% (so với 15% hiện tại). Vui lòng đọc thông báo đầy đủ trong phần Trợ giúp.',
    createdAt: '2 tuần trước',
    isoDate: '2024-11-25T08:00:00',
    read: true,
    ctaLabel: 'Đọc thông báo đầy đủ',
    ctaHref: '/help',
  },
]
