import type { Place, PlaceReview } from '@types/place'

const IMG = (seed: string, w = 1200) =>
  `https://images.unsplash.com/photo-${seed}?auto=format&fit=crop&w=${w}&q=80`
const AV = (seed: string) =>
  `https://images.unsplash.com/photo-${seed}?auto=format&fit=crop&w=200&q=80`

export const PLACE_CATEGORIES = [
  { key: 'all', label: 'Tất cả', icon: 'apps' },
  { key: 'beach', label: 'Biển', icon: 'beach_access' },
  { key: 'mountain', label: 'Núi', icon: 'terrain' },
  { key: 'culture', label: 'Văn hoá', icon: 'temple_buddhist' },
  { key: 'historical', label: 'Lịch sử', icon: 'castle' },
  { key: 'food', label: 'Ẩm thực', icon: 'restaurant' },
  { key: 'city', label: 'Thành phố', icon: 'location_city' },
  { key: 'island', label: 'Đảo', icon: 'sailing' },
  { key: 'nature', label: 'Thiên nhiên', icon: 'park' },
  { key: 'adventure', label: 'Phiêu lưu', icon: 'paragliding' },
] as const

export const PROVINCES = [
  { key: 'all', label: 'Toàn quốc' },
  { key: 'Quảng Ninh', label: 'Quảng Ninh' },
  { key: 'Lào Cai', label: 'Lào Cai' },
  { key: 'Hà Giang', label: 'Hà Giang' },
  { key: 'Quảng Nam', label: 'Quảng Nam' },
  { key: 'Thừa Thiên Huế', label: 'Thừa Thiên Huế' },
  { key: 'Quảng Bình', label: 'Quảng Bình' },
  { key: 'Khánh Hoà', label: 'Khánh Hoà' },
  { key: 'Kiên Giang', label: 'Kiên Giang' },
  { key: 'TP. HCM', label: 'TP. HCM' },
] as const

const reviews1: PlaceReview[] = [
  {
    id: 'pr1',
    authorId: 'u1',
    authorName: 'Maya Lee',
    authorAvatar: AV('1502823403499-6ccfcf4fb453'),
    rating: 5,
    date: '2 tuần trước',
    content:
      'Một trong những kỳ quan đẹp nhất Việt Nam. Đi cano sáng sớm để tránh đông là chuẩn bài.',
    helpfulCount: 24,
  },
  {
    id: 'pr2',
    authorId: 'u2',
    authorName: 'Alex Nguyễn',
    authorAvatar: AV('1539571696357-5a69c17a67c6'),
    rating: 4,
    date: '1 tháng trước',
    content:
      'Cảnh đẹp nhưng khá đông. Nên book tour 2 ngày 1 đêm để cảm nhận đầy đủ.',
    helpfulCount: 12,
  },
]

const reviewsGeneric: PlaceReview[] = [
  {
    id: 'prg1',
    authorId: 'u3',
    authorName: 'Mai Phùng',
    authorAvatar: AV('1573496359142-b8d87734a5a2'),
    rating: 5,
    date: '3 ngày trước',
    content: 'Cảm xúc khó tả, sẽ quay lại lần thứ 2!',
    helpfulCount: 8,
  },
  {
    id: 'prg2',
    authorId: 'u4',
    authorName: 'Sơn Hoàng',
    authorAvatar: AV('1507003211169-0a1dd7228f2d'),
    rating: 4,
    date: '1 tuần trước',
    content: 'Đáng đến một lần trong đời.',
    helpfulCount: 5,
  },
]

const standardHours = [
  { day: 1, open: '07:00', close: '18:00' },
  { day: 2, open: '07:00', close: '18:00' },
  { day: 3, open: '07:00', close: '18:00' },
  { day: 4, open: '07:00', close: '18:00' },
  { day: 5, open: '07:00', close: '18:00' },
  { day: 6, open: '06:00', close: '19:00' },
  { day: 0, open: '06:00', close: '19:00' },
]

export const mockPlaces: Place[] = [
  {
    id: 'pl1',
    slug: 'vinh-ha-long',
    name: 'Vịnh Hạ Long',
    description: 'Kỳ quan thiên nhiên thế giới với hàng nghìn đảo đá vôi.',
    longDescription:
      'Vịnh Hạ Long là một vịnh nhỏ thuộc phần bờ Tây vịnh Bắc Bộ tại khu vực biển Đông Bắc Việt Nam, bao gồm vùng biển đảo của thành phố Hạ Long, Cẩm Phả và một phần của huyện đảo Vân Đồn. UNESCO công nhận là Di sản thiên nhiên thế giới năm 1994 và một lần nữa năm 2000 vì giá trị địa chất, địa mạo độc đáo.',
    category: 'island',
    province: 'Quảng Ninh',
    city: 'TP. Hạ Long',
    address: 'Cảng tàu Tuần Châu, TP. Hạ Long',
    coverImage: IMG('1528127269322-539801943592'),
    gallery: [
      IMG('1528127269322-539801943592'),
      IMG('1528127269322-539801943592', 1400),
      IMG('1528127269322-539801943592', 1100),
      IMG('1528127269322-539801943592', 1300),
    ],
    rating: 4.9,
    reviewCount: 1284,
    duration: '1-3 ngày',
    bestTime: 'Tháng 10 - Tháng 4',
    entranceFee: '₫290,000 - ₫600,000',
    openingHours: standardHours,
    tags: ['UNESCO', 'Di sản', 'Du thuyền'],
    highlights: ['Hang Sửng Sốt', 'Đảo Titop', 'Làng chài Cửa Vạn', 'Kayak'],
    coordinates: { lat: 20.9101, lng: 107.1839 },
    relatedIds: ['pl5', 'pl8', 'pl3'],
    reviews: reviews1,
  },
  {
    id: 'pl2',
    slug: 'sapa',
    name: 'Sapa',
    description: 'Thị trấn trên mây với ruộng bậc thang vàng óng và văn hoá H\'mông.',
    longDescription:
      'Sapa là một thị trấn vùng cao thuộc huyện Sa Pa, tỉnh Lào Cai, Việt Nam. Nổi tiếng với khí hậu mát mẻ quanh năm, ruộng bậc thang Mường Hoa và nét văn hoá đặc sắc của người H\'mông, Dao đỏ. Đỉnh Fansipan — nóc nhà Đông Dương — cao 3.143m.',
    category: 'mountain',
    province: 'Lào Cai',
    city: 'Thị xã Sa Pa',
    coverImage: IMG('1528127269322-539801943592', 1300),
    gallery: [
      IMG('1528127269322-539801943592'),
      IMG('1528127269322-539801943592', 1100),
      IMG('1528127269322-539801943592', 900),
    ],
    rating: 4.8,
    reviewCount: 892,
    duration: '2-3 ngày',
    bestTime: 'Tháng 9 - Tháng 11 (lúa chín)',
    entranceFee: 'Miễn phí',
    tags: ['Trekking', 'Ruộng bậc thang', 'Fansipan'],
    highlights: ['Bản Cát Cát', 'Mường Hoa', 'Đèo Ô Quy Hồ', 'Cáp treo Fansipan'],
    coordinates: { lat: 22.3364, lng: 103.844 },
    relatedIds: ['pl3', 'pl7'],
    reviews: reviewsGeneric,
  },
  {
    id: 'pl3',
    slug: 'ha-giang-loop',
    name: 'Hà Giang Loop',
    description: 'Cung đường motorbike huyền thoại qua những đèo đá tai mèo.',
    longDescription:
      'Hà Giang Loop là cung đường khoảng 350km xuyên qua các huyện Quản Bạ, Yên Minh, Đồng Văn và Mèo Vạc — vùng cao nguyên đá Đồng Văn được UNESCO công nhận là công viên địa chất toàn cầu. Đèo Mã Pí Lèng được mệnh danh là "vua của các đèo" Việt Nam.',
    category: 'adventure',
    province: 'Hà Giang',
    coverImage: IMG('1528127269322-539801943592', 1400),
    gallery: [IMG('1528127269322-539801943592'), IMG('1528127269322-539801943592', 1100)],
    rating: 4.95,
    reviewCount: 1567,
    duration: '3-4 ngày',
    bestTime: 'Tháng 10 - Tháng 11 (hoa tam giác mạch)',
    entranceFee: 'Miễn phí',
    tags: ['Motorbike', 'Đèo', 'Cao nguyên đá'],
    highlights: ['Đèo Mã Pí Lèng', 'Cột cờ Lũng Cú', 'Phố cổ Đồng Văn', 'Sông Nho Quế'],
    relatedIds: ['pl2', 'pl1'],
    reviews: reviewsGeneric,
  },
  {
    id: 'pl4',
    slug: 'pho-co-hoi-an',
    name: 'Phố cổ Hội An',
    description: 'Phố lồng đèn rực rỡ và kiến trúc Đông – Tây giao thoa hơn 400 năm.',
    longDescription:
      'Phố cổ Hội An là một đô thị cổ nằm ở hạ lưu sông Thu Bồn, được UNESCO công nhận là Di sản văn hoá thế giới năm 1999. Nổi tiếng với kiến trúc cổ Trung Hoa pha trộn Nhật Bản và Pháp, lễ hội đèn lồng vào đêm rằm hằng tháng và ẩm thực đường phố.',
    category: 'culture',
    province: 'Quảng Nam',
    city: 'TP. Hội An',
    address: 'Phố cổ, P. Minh An, TP. Hội An',
    coverImage: IMG('1528127269322-539801943592', 1100),
    gallery: [IMG('1528127269322-539801943592'), IMG('1528127269322-539801943592', 1300)],
    rating: 4.9,
    reviewCount: 2103,
    duration: '1-2 ngày',
    bestTime: 'Tháng 2 - Tháng 4',
    entranceFee: '₫120,000 (vé tham quan)',
    openingHours: standardHours,
    tags: ['UNESCO', 'Đèn lồng', 'Kiến trúc cổ'],
    highlights: ['Chùa Cầu', 'Nhà cổ Tấn Ký', 'Hội quán Phúc Kiến', 'Lễ hội đèn lồng'],
    relatedIds: ['pl5', 'pl1'],
    reviews: reviewsGeneric,
  },
  {
    id: 'pl5',
    slug: 'co-do-hue',
    name: 'Cố đô Huế',
    description: 'Kinh thành triều Nguyễn — di sản kiến trúc, lăng tẩm và nhã nhạc cung đình.',
    longDescription:
      'Quần thể di tích Cố đô Huế là quần thể di tích lịch sử văn hoá ở Huế, kinh đô của triều Nguyễn (1802 – 1945). UNESCO công nhận là Di sản văn hoá thế giới năm 1993. Bao gồm Hoàng thành, Tử Cấm Thành, các lăng tẩm vua Nguyễn và sông Hương — núi Ngự thơ mộng.',
    category: 'historical',
    province: 'Thừa Thiên Huế',
    city: 'TP. Huế',
    coverImage: IMG('1528127269322-539801943592', 1200),
    gallery: [IMG('1528127269322-539801943592')],
    rating: 4.85,
    reviewCount: 1450,
    duration: '2 ngày',
    bestTime: 'Tháng 1 - Tháng 4',
    entranceFee: '₫200,000 (Đại Nội)',
    openingHours: standardHours,
    tags: ['UNESCO', 'Triều Nguyễn', 'Lăng tẩm'],
    highlights: ['Đại Nội', 'Lăng Tự Đức', 'Lăng Khải Định', 'Sông Hương'],
    relatedIds: ['pl4', 'pl6'],
    reviews: reviewsGeneric,
  },
  {
    id: 'pl6',
    slug: 'phong-nha-ke-bang',
    name: 'Phong Nha - Kẻ Bàng',
    description: 'Vương quốc hang động — nơi có hang Sơn Đoòng lớn nhất thế giới.',
    longDescription:
      'Vườn quốc gia Phong Nha - Kẻ Bàng là một vườn quốc gia tại huyện Bố Trạch và Minh Hoá, tỉnh Quảng Bình. UNESCO công nhận 2 lần (2003 và 2015). Nổi tiếng với hệ thống hang động kỳ vĩ — đặc biệt hang Sơn Đoòng được khám phá năm 2009 là hang động tự nhiên lớn nhất thế giới.',
    category: 'nature',
    province: 'Quảng Bình',
    city: 'H. Bố Trạch',
    coverImage: IMG('1528127269322-539801943592', 1500),
    gallery: [IMG('1528127269322-539801943592'), IMG('1528127269322-539801943592', 900)],
    rating: 4.95,
    reviewCount: 980,
    duration: '2-4 ngày',
    bestTime: 'Tháng 3 - Tháng 8',
    entranceFee: '₫150,000 - ₫3,500,000 (tour Sơn Đoòng)',
    openingHours: standardHours,
    tags: ['UNESCO', 'Hang động', 'Sơn Đoòng'],
    highlights: ['Hang Sơn Đoòng', 'Động Phong Nha', 'Hang Én', 'Sông Chày'],
    relatedIds: ['pl5', 'pl3'],
    reviews: reviewsGeneric,
  },
  {
    id: 'pl7',
    slug: 'nha-trang',
    name: 'Nha Trang',
    description: 'Bãi biển dài 7km, nước trong xanh và đảo lặn ngắm san hô.',
    longDescription:
      'Nha Trang là thành phố ven biển và trung tâm chính trị, kinh tế, văn hoá của tỉnh Khánh Hoà. Vịnh Nha Trang là một trong 29 vịnh đẹp nhất thế giới. Nổi tiếng với các đảo lặn biển, tháp Po Nagar Chăm cổ và ẩm thực hải sản.',
    category: 'beach',
    province: 'Khánh Hoà',
    city: 'TP. Nha Trang',
    coverImage: IMG('1528127269322-539801943592', 1300),
    gallery: [IMG('1528127269322-539801943592')],
    rating: 4.7,
    reviewCount: 2156,
    duration: '3-4 ngày',
    bestTime: 'Tháng 1 - Tháng 8',
    entranceFee: 'Miễn phí',
    tags: ['Biển', 'Lặn', 'Hải sản'],
    highlights: ['Hòn Mun', 'Vinpearl Land', 'Tháp Bà Ponagar', 'Bùn khoáng Tháp Bà'],
    relatedIds: ['pl8', 'pl1'],
    reviews: reviewsGeneric,
  },
  {
    id: 'pl8',
    slug: 'phu-quoc',
    name: 'Phú Quốc',
    description: 'Đảo ngọc với bãi tắm cát trắng và mặt trời lặn đẹp nhất Việt Nam.',
    longDescription:
      'Phú Quốc là đảo lớn nhất Việt Nam, thuộc tỉnh Kiên Giang. Được mệnh danh là "đảo ngọc" với những bãi tắm cát trắng mịn, nước biển trong xanh và rừng nguyên sinh. Nổi tiếng với nước mắm Phú Quốc, ngọc trai và cáp treo dài nhất thế giới.',
    category: 'island',
    province: 'Kiên Giang',
    city: 'TP. Phú Quốc',
    coverImage: IMG('1528127269322-539801943592', 1400),
    gallery: [IMG('1528127269322-539801943592'), IMG('1528127269322-539801943592', 1000)],
    rating: 4.8,
    reviewCount: 1789,
    duration: '3-5 ngày',
    bestTime: 'Tháng 11 - Tháng 4',
    entranceFee: 'Miễn phí',
    tags: ['Đảo', 'Biển', 'Cáp treo'],
    highlights: ['Bãi Sao', 'Cáp treo Hòn Thơm', 'Vinpearl Safari', 'Sunset Sanato'],
    relatedIds: ['pl1', 'pl7'],
    reviews: reviewsGeneric,
  },
]
