import type { Trip, TripGuide, TripMember } from '@types/trip'
import type { Guide, Post } from '@types/post'

const IMG = (seed: string) =>
  `https://images.unsplash.com/photo-${seed}?auto=format&fit=crop&w=1200&q=80`

export const mockGuides: Guide[] = [
  {
    id: 'g1',
    name: 'Minh Nguyen',
    avatar: IMG('1544005313-94ddf0286df2'),
    location: 'Ha Giang & Sapa',
    rating: 4.9,
  },
  {
    id: 'g2',
    name: 'Linh Tran',
    avatar: IMG('1494790108377-be9c29b29330'),
    location: 'Hue & Da Nang',
    rating: 5.0,
  },
  {
    id: 'g3',
    name: 'Son Hoang',
    avatar: IMG('1507003211169-0a1dd7228f2d'),
    location: 'Ho Chi Minh City',
    rating: 4.8,
  },
  {
    id: 'g4',
    name: 'Mai Phung',
    avatar: IMG('1573496359142-b8d87734a5a2'),
    location: 'Mekong Delta',
    rating: 4.9,
  },
]

export const mockPosts: Post[] = [
  {
    id: 'p1',
    authorId: 'u1',
    authorName: 'Alex Nguyen',
    authorAvatar: IMG('1539571696357-5a69c17a67c6'),
    location: 'Hoi An',
    postedAt: '2 hours ago',
    title: 'Midnight in the Lantern City',
    excerpt:
      'Found a quiet alley away from the crowds. The lanterns hit different when the streets are empty...',
    image: IMG('1528127269322-539801943592'),
    likes: 1200,
    comments: 84,
  },
  {
    id: 'p2',
    authorId: 'u2',
    authorName: 'Elena Tran',
    authorAvatar: IMG('1438761681033-6461ffad8d80'),
    location: 'Ha Giang',
    postedAt: '5 hours ago',
    title: 'The Loop that Changes You',
    excerpt: 'Finally conquered the Ma Pi Leng pass. Words cannot describe the scale of these mountains.',
    image: IMG('1528127269322-539801943592'),
    likes: 3400,
    comments: 120,
  },
  {
    id: 'p3',
    authorId: 'u3',
    authorName: 'Maya Lee',
    authorAvatar: IMG('1502823403499-6ccfcf4fb453'),
    location: 'Hue',
    postedAt: 'Yesterday',
    title: 'Imperial Echoes',
    excerpt:
      'Walking through the Forbidden Purple City felt like stepping through time. The detail is insane.',
    image: IMG('1528127269322-539801943592'),
    likes: 2100,
    comments: 45,
  },
]

const sampleCreator: TripMember = {
  id: 'c1',
  name: 'Linh Nguyen',
  avatar: IMG('1494790108377-be9c29b29330'),
  role: 'leader',
}

const sampleMembers: TripMember[] = [
  {
    id: 'm1',
    name: 'Alex Nguyen',
    avatar: IMG('1539571696357-5a69c17a67c6'),
    role: 'member',
  },
  {
    id: 'm2',
    name: 'Elena Tran',
    avatar: IMG('1438761681033-6461ffad8d80'),
    role: 'member',
  },
  {
    id: 'm3',
    name: 'Maya Lee',
    avatar: IMG('1502823403499-6ccfcf4fb453'),
    role: 'member',
  },
  {
    id: 'm4',
    name: 'Sơn Hoàng',
    avatar: IMG('1507003211169-0a1dd7228f2d'),
    role: 'member',
  },
]

const guideHaLong: TripGuide = {
  id: 'tg1',
  name: 'Captain Đức',
  avatar: IMG('1544005313-94ddf0286df2'),
  region: 'Vịnh Hạ Long & Cát Bà',
  rating: 4.95,
  reviewCount: 312,
  yearsExperience: 12,
  languages: ['Tiếng Việt', 'English', '日本語'],
  specialties: ['Du thuyền', 'Hang động', 'Hải sản địa phương'],
  bio: 'Sinh ra giữa lòng vịnh, Đức biết từng hang đá và bãi cát ẩn — và cách kể câu chuyện về chúng.',
  verified: true,
}

const guideHoiAn: TripGuide = {
  id: 'tg2',
  name: 'Chị Hoa',
  avatar: IMG('1573496359142-b8d87734a5a2'),
  region: 'Hội An & Đà Nẵng',
  rating: 4.9,
  reviewCount: 248,
  yearsExperience: 9,
  languages: ['Tiếng Việt', 'English'],
  specialties: ['Ẩm thực phố cổ', 'Đèn lồng', 'Nghề thủ công'],
  bio: 'Đầu bếp và hướng dẫn viên — Chị Hoa dẫn bạn vào những con hẻm chỉ người Hội An mới biết.',
  verified: true,
}

const guidePhuQuoc: TripGuide = {
  id: 'tg3',
  name: 'Anh Tùng',
  avatar: IMG('1500648767791-00dcc994a43e'),
  region: 'Phú Quốc & An Thới',
  rating: 4.85,
  reviewCount: 187,
  yearsExperience: 7,
  languages: ['Tiếng Việt', 'English'],
  specialties: ['Lặn biển', 'Câu cá', 'Đảo hoang'],
  bio: 'Cựu ngư dân chuyển nghề hướng dẫn — biết mọi rạn san hô và bãi tắm bí mật của đảo.',
  verified: true,
}

const guideSapa: TripGuide = {
  id: 'tg4',
  name: 'Sùng A Páo',
  avatar: IMG('1507003211169-0a1dd7228f2d'),
  region: 'Sapa & Y Tý',
  rating: 4.92,
  reviewCount: 156,
  yearsExperience: 8,
  languages: ['Tiếng Việt', 'H\'mông', 'English'],
  specialties: ['Trekking', 'Văn hoá H\'mông', 'Ruộng bậc thang'],
  bio: 'Người con của núi rừng Tây Bắc — Páo dẫn bạn đi xa hơn những gì bản đồ Google biết.',
  verified: true,
}

export const mockTrips: Trip[] = [
  {
    id: 't1',
    title: 'Luxury Cruise & Hidden Caves Exploration',
    description:
      'A curated escape to Ha Long Bay where the sunrise meets the soul. Three days aboard a premium junk boat.',
    destination: 'Ha Long Bay',
    category: 'island',
    coverImage: IMG('1528127269322-539801943592'),
    startDate: 'Oct 12',
    endDate: 'Oct 15',
    durationDays: 3,
    priceFrom: 450,
    currency: '$',
    rating: 4.9,
    maxMembers: 6,
    memberCount: 4,
    members: sampleMembers.slice(0, 3),
    creator: sampleCreator,
    guide: guideHaLong,
    tags: ['Adventure', 'Cultural'],
    itinerary: [],
    isJoined: true,
  },
  {
    id: 't2',
    title: 'Lantern Magic & Ancient Town Foodie Tour',
    description: 'Taste the soul of Hoi An by lantern-light — food, culture, craft.',
    destination: 'Hoi An',
    category: 'food',
    coverImage: IMG('1528127269322-539801943592'),
    startDate: 'Nov 05',
    endDate: 'Nov 08',
    durationDays: 3,
    priceFrom: 320,
    currency: '$',
    rating: 5.0,
    maxMembers: 4,
    memberCount: 2,
    members: sampleMembers.slice(0, 1),
    creator: sampleCreator,
    guide: guideHoiAn,
    tags: ['Food', 'Cultural'],
    itinerary: [],
  },
  {
    id: 't3',
    title: 'Phu Quoc 3N2D: Pearl Island Escape',
    description: 'Three days chasing sunsets and hidden coves on Vietnam’s pearl island.',
    destination: 'Phu Quoc',
    category: 'beach',
    coverImage: IMG('1528127269322-539801943592'),
    startDate: 'Dec 01',
    endDate: 'Dec 03',
    durationDays: 3,
    priceFrom: 429,
    currency: '$',
    rating: 4.8,
    maxMembers: 12,
    memberCount: 6,
    members: sampleMembers,
    creator: sampleCreator,
    guide: guidePhuQuoc,
    tags: ['Beach', 'Island Life'],
    itinerary: [],
    isJoined: true,
  },
  {
    id: 't4',
    title: 'Sapa Trekking: Rice Terraces & Hill Tribes',
    description: 'Two-day immersive trek through Muong Hoa valley and overnight homestay.',
    destination: 'Sapa',
    category: 'mountain',
    coverImage: IMG('1528127269322-539801943592'),
    startDate: 'Jan 14',
    endDate: 'Jan 16',
    durationDays: 2,
    priceFrom: 240,
    currency: '$',
    rating: 4.7,
    maxMembers: 8,
    memberCount: 3,
    members: sampleMembers.slice(0, 2),
    creator: sampleCreator,
    guide: guideSapa,
    tags: ['Mountain', 'Culture'],
    itinerary: [],
  },
  {
    id: 't5',
    title: 'Saigon After Dark: Hidden Bites Tour',
    description: 'A nocturnal feast through Ho Chi Minh City’s alleys with local foodies.',
    destination: 'Ho Chi Minh City',
    category: 'city',
    coverImage: IMG('1528127269322-539801943592'),
    startDate: 'Feb 02',
    endDate: 'Feb 02',
    durationDays: 1,
    priceFrom: 95,
    currency: '$',
    rating: 4.9,
    maxMembers: 10,
    memberCount: 7,
    members: sampleMembers,
    creator: sampleCreator,
    guide: guideHoiAn,
    tags: ['Food', 'City'],
    itinerary: [],
  },
  {
    id: 't6',
    title: 'Ha Giang Loop: 4 Days of Mountain Roads',
    description: 'A self-guided motorbike journey through Vietnam’s wildest northern frontier.',
    destination: 'Ha Giang',
    category: 'adventure',
    coverImage: IMG('1528127269322-539801943592'),
    startDate: 'Mar 18',
    endDate: 'Mar 21',
    durationDays: 4,
    priceFrom: 380,
    currency: '$',
    rating: 4.95,
    maxMembers: 6,
    memberCount: 5,
    members: sampleMembers.slice(0, 3),
    creator: sampleCreator,
    guide: guideSapa,
    tags: ['Adventure', 'Mountain'],
    itinerary: [],
  },
]
