import type { HireableGuide } from '@types/trip'

const IMG = (seed: string, w = 800) =>
  `https://images.unsplash.com/photo-${seed}?auto=format&fit=crop&w=${w}&q=80`

export const REGION_FILTERS = [
  { key: 'all', label: 'Tất cả', icon: 'public' },
  { key: 'north', label: 'Miền Bắc', icon: 'terrain' },
  { key: 'central', label: 'Miền Trung', icon: 'temple_buddhist' },
  { key: 'south', label: 'Miền Nam', icon: 'beach_access' },
  { key: 'island', label: 'Đảo', icon: 'sailing' },
] as const

export const CATEGORY_FILTERS = [
  { key: 'all', label: 'Tất cả lĩnh vực', icon: 'apps' },
  { key: 'mountain', label: 'Núi & Trekking', icon: 'terrain' },
  { key: 'food', label: 'Ẩm thực', icon: 'restaurant' },
  { key: 'culture', label: 'Văn hoá', icon: 'temple_buddhist' },
  { key: 'beach', label: 'Biển', icon: 'beach_access' },
  { key: 'city', label: 'Thành phố', icon: 'location_city' },
  { key: 'adventure', label: 'Phiêu lưu', icon: 'hiking' },
  { key: 'island', label: 'Đảo', icon: 'sailing' },
] as const

export const mockHireableGuides: HireableGuide[] = [
  {
    id: 'hg1',
    name: 'Captain Đức',
    avatar: IMG('1544005313-94ddf0286df2', 400),
    coverImage: IMG('1528127269322-539801943592', 1200),
    region: 'Vịnh Hạ Long & Cát Bà',
    regionKeys: ['north', 'island'],
    rating: 4.95,
    reviewCount: 312,
    yearsExperience: 12,
    languages: ['Tiếng Việt', 'English', '日本語'],
    specialties: ['Du thuyền', 'Hang động', 'Hải sản địa phương'],
    categoryKeys: ['island', 'beach', 'food'],
    bio: 'Sinh ra giữa lòng vịnh, Đức biết từng hang đá và bãi cát ẩn — và cách kể câu chuyện về chúng.',
    verified: true,
    pricePerDay: 1200000,
    currency: '₫',
    availability: 'available',
    availabilityLabel: 'Còn lịch tháng 12',
    toursCompleted: 480,
    responseTime: 'trong 1 giờ',
    highlights: ['Top Rated', 'Local Expert', 'Superhost'],
  },
  {
    id: 'hg2',
    name: 'Chị Hoa',
    avatar: IMG('1573496359142-b8d87734a5a2', 400),
    coverImage: IMG('1528127269322-539801943592', 1200),
    region: 'Hội An & Đà Nẵng',
    regionKeys: ['central'],
    rating: 4.9,
    reviewCount: 248,
    yearsExperience: 9,
    languages: ['Tiếng Việt', 'English'],
    specialties: ['Ẩm thực phố cổ', 'Đèn lồng', 'Nghề thủ công'],
    categoryKeys: ['food', 'culture', 'city'],
    bio: 'Đầu bếp và hướng dẫn viên — Chị Hoa dẫn bạn vào những con hẻm chỉ người Hội An mới biết.',
    verified: true,
    pricePerDay: 950000,
    currency: '₫',
    availability: 'available',
    availabilityLabel: 'Còn lịch tuần tới',
    toursCompleted: 312,
    responseTime: 'trong 30 phút',
    highlights: ['Top Rated', 'Foodie Choice'],
  },
  {
    id: 'hg3',
    name: 'Sùng A Páo',
    avatar: IMG('1507003211169-0a1dd7228f2d', 400),
    coverImage: IMG('1528127269322-539801943592', 1200),
    region: 'Sapa & Y Tý',
    regionKeys: ['north'],
    rating: 4.92,
    reviewCount: 156,
    yearsExperience: 8,
    languages: ['Tiếng Việt', "H'mông", 'English'],
    specialties: ['Trekking', "Văn hoá H'mông", 'Ruộng bậc thang'],
    categoryKeys: ['mountain', 'culture', 'adventure'],
    bio: 'Người con của núi rừng Tây Bắc — Páo dẫn bạn đi xa hơn những gì bản đồ Google biết.',
    verified: true,
    pricePerDay: 850000,
    currency: '₫',
    availability: 'busy',
    availabilityLabel: 'Bận đến 20/12',
    toursCompleted: 220,
    responseTime: 'trong 2 giờ',
    highlights: ['Local Expert'],
  },
  {
    id: 'hg4',
    name: 'Anh Tùng',
    avatar: IMG('1500648767791-00dcc994a43e', 400),
    coverImage: IMG('1528127269322-539801943592', 1200),
    region: 'Phú Quốc & An Thới',
    regionKeys: ['south', 'island'],
    rating: 4.85,
    reviewCount: 187,
    yearsExperience: 7,
    languages: ['Tiếng Việt', 'English'],
    specialties: ['Lặn biển', 'Câu cá', 'Đảo hoang'],
    categoryKeys: ['beach', 'island', 'adventure'],
    bio: 'Cựu ngư dân chuyển nghề hướng dẫn — biết mọi rạn san hô và bãi tắm bí mật của đảo.',
    verified: true,
    pricePerDay: 1100000,
    currency: '₫',
    availability: 'available',
    availabilityLabel: 'Còn lịch cuối tuần',
    toursCompleted: 198,
    responseTime: 'trong 45 phút',
    highlights: ['Diving Pro'],
  },
  {
    id: 'hg5',
    name: 'Linh Nguyễn',
    avatar: IMG('1494790108377-be9c29b29330', 400),
    coverImage: IMG('1528127269322-539801943592', 1200),
    region: 'TP. Hồ Chí Minh & Mekong',
    regionKeys: ['south'],
    rating: 4.88,
    reviewCount: 220,
    yearsExperience: 6,
    languages: ['Tiếng Việt', 'English', 'Français'],
    specialties: ['Ẩm thực đường phố', 'Lịch sử', 'Cafe'],
    categoryKeys: ['food', 'city', 'culture'],
    bio: 'Sinh viên kiến trúc cũ — kể về Sài Gòn qua từng ô gạch và mùi cafe sữa đá.',
    verified: false,
    pricePerDay: 700000,
    currency: '₫',
    availability: 'available',
    availabilityLabel: 'Linh hoạt',
    toursCompleted: 140,
    responseTime: 'trong 1 giờ',
    highlights: ['Foodie Choice', 'New'],
  },
  {
    id: 'hg6',
    name: 'Mai Phùng',
    avatar: IMG('1438761681033-6461ffad8d80', 400),
    coverImage: IMG('1528127269322-539801943592', 1200),
    region: 'Huế & Phong Nha',
    regionKeys: ['central'],
    rating: 4.94,
    reviewCount: 178,
    yearsExperience: 10,
    languages: ['Tiếng Việt', 'English'],
    specialties: ['Hang động', 'Lịch sử triều Nguyễn', 'Trekking'],
    categoryKeys: ['mountain', 'culture', 'adventure'],
    bio: 'Hướng dẫn viên có chứng chỉ leo núi quốc tế — chuyên các tour hang động dài ngày.',
    verified: true,
    pricePerDay: 1450000,
    currency: '₫',
    availability: 'fully-booked',
    availabilityLabel: 'Hết lịch tháng này',
    toursCompleted: 360,
    responseTime: 'trong 3 giờ',
    highlights: ['Top Rated', 'Adventure Pro'],
  },
]
