/**
 * Static persona data for the guide seeder. Kept separate so the run script
 * stays focused on persistence logic and the file size stays under our 150-line
 * editing limit.
 */
import type { GuidePersona, TravelerPersona } from './seed-guides.types'

export const GUIDE_PERSONAS: GuidePersona[] = [
  {
    email: 'guide.minh@tripmate.local',
    name: 'Minh Trần',
    handle: 'minh.tran',
    avatar: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=200&q=80',
    region: 'Hạ Long & Đông Bắc',
    regionKeys: ['ha-long', 'north'],
    categoryKeys: ['beach', 'island', 'adventure'],
    languages: ['Vietnamese', 'English'],
    specialties: ['Du thuyền', 'Kayak', 'Hang động'],
    bio: 'HDV chuyên tour vịnh Hạ Long với 5 năm kinh nghiệm.',
    yearsExperience: 5,
    pricePerDay: 1_200_000,
    rating: 4.9,
    reviewCount: 87,
    toursCompleted: 142,
    responseTime: 'trong 1 giờ',
    coverImage: 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1200&q=80',
    availabilityLabel: 'Còn lịch tháng này',
    highlights: ['Top Rated', 'Local Expert'],
  },
  {
    email: 'guide.thao@tripmate.local',
    name: 'Thảo Nguyễn',
    handle: 'thao.nguyen',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80',
    region: 'Sapa & Tây Bắc',
    regionKeys: ['sa-pa', 'north'],
    categoryKeys: ['mountain', 'culture', 'adventure'],
    languages: ['Vietnamese', 'English', 'French'],
    specialties: ['Trekking', 'Homestay', 'Bản làng'],
    bio: 'Sinh ra tại Sapa, dẫn tour trekking băng qua bản H\'Mông và Dao Đỏ.',
    yearsExperience: 7,
    pricePerDay: 950_000,
    rating: 4.95,
    reviewCount: 124,
    toursCompleted: 210,
    responseTime: 'trong 30 phút',
    coverImage: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=1200&q=80',
    availabilityLabel: 'Đang mở booking',
    highlights: ['Top Rated', 'Cultural'],
  },
  {
    email: 'guide.long@tripmate.local',
    name: 'Long Phạm',
    handle: 'long.pham',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    region: 'Hội An & Đà Nẵng',
    regionKeys: ['hoi-an', 'da-nang', 'central'],
    categoryKeys: ['culture', 'food', 'beach'],
    languages: ['Vietnamese', 'English', 'Japanese'],
    specialties: ['Phố cổ', 'Ẩm thực', 'Tour ban đêm'],
    bio: 'HDV tour ẩm thực miền Trung, từng dẫn 200+ tour Hội An đêm.',
    yearsExperience: 6,
    pricePerDay: 1_100_000,
    rating: 4.8,
    reviewCount: 96,
    toursCompleted: 187,
    responseTime: 'trong 2 giờ',
    coverImage: 'https://images.unsplash.com/photo-1558005530-a7958896ec60?auto=format&fit=crop&w=1200&q=80',
    availabilityLabel: 'Còn lịch cuối tuần',
    highlights: ['Foodie', 'Local Expert'],
  },
  {
    email: 'guide.an@tripmate.local',
    name: 'An Hoàng',
    handle: 'an.hoang',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    region: 'Phú Quốc',
    regionKeys: ['phu-quoc', 'south'],
    categoryKeys: ['island', 'beach', 'food'],
    languages: ['Vietnamese', 'English'],
    specialties: ['Lặn biển', 'Câu cá', 'Tour đảo'],
    bio: 'Người Phú Quốc bản địa, chuyên tour câu cá và lặn ngắm san hô.',
    yearsExperience: 4,
    pricePerDay: 1_500_000,
    rating: 4.7,
    reviewCount: 58,
    toursCompleted: 92,
    responseTime: 'trong 1 giờ',
    coverImage: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    availabilityLabel: 'Sẵn sàng',
    highlights: ['Diving Pro'],
  },
  {
    email: 'guide.huong@tripmate.local',
    name: 'Hương Lê',
    handle: 'huong.le',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=200&q=80',
    region: 'Hà Giang',
    regionKeys: ['ha-giang', 'north'],
    categoryKeys: ['mountain', 'adventure', 'culture'],
    languages: ['Vietnamese', 'English'],
    specialties: ['Motorbike Tour', 'Mã Pí Lèng', 'Lễ hội'],
    bio: 'Dẫn tour xe máy Hà Giang 4N3Đ qua những cung đường đẹp nhất Việt Nam.',
    yearsExperience: 8,
    pricePerDay: 1_300_000,
    rating: 4.92,
    reviewCount: 156,
    toursCompleted: 245,
    responseTime: 'trong 2 giờ',
    coverImage: 'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=1200&q=80',
    availabilityLabel: 'Còn lịch tháng tới',
    highlights: ['Adventure', 'Top Rated'],
  },
]

export const TRAVELER_PERSONAS: TravelerPersona[] = [
  { email: 't.quan@tripmate.local', name: 'Quân Đỗ', handle: 'quan.do', avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80' },
  { email: 't.mai@tripmate.local', name: 'Mai Vũ', handle: 'mai.vu', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80' },
  { email: 't.duc@tripmate.local', name: 'Đức Lê', handle: 'duc.le', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80' },
  { email: 't.lan@tripmate.local', name: 'Lan Phạm', handle: 'lan.pham', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80' },
  { email: 't.hoa@tripmate.local', name: 'Hoa Trần', handle: 'hoa.tran', avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=200&q=80' },
  { email: 't.tu@tripmate.local', name: 'Tú Nguyễn', handle: 'tu.nguyen', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80' },
  { email: 't.bao@tripmate.local', name: 'Bảo Hoàng', handle: 'bao.hoang', avatar: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=200&q=80' },
  { email: 't.linh@tripmate.local', name: 'Linh Đặng', handle: 'linh.dang', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=200&q=80' },
]
